export enum TypePlante {
  Ail = 'Ail',
  Aubergine = 'Ail',
  Betterave = 'Ail',
  Carotte = 'Ail',
  Concombre = 'Ail',
  Céléri = 'Ail',
  Chou = 'Ail',
  Courge = 'Ail',
  Courgette = 'Ail',
  Fenouil = 'Ail',
  Fraisier = 'Ail',
  Haricot = 'Ail',
  Laitue = 'Ail',
  Melon = 'Ail',
  Poireau = 'Ail',
  Pois = 'Ail',
  Poivron = 'Ail',
  Radis = 'Ail',
  Tomate = 'Ail',
}
